routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware('auth')->group(function(){
  Route::get('/', 'CampaignController@index')->name('home');

  Route::resource('/templates', 'TemplateController');

  Route::resource('/campaigns', 'CampaignController');
  Route::get('/campaigns/{campaign}/preview', 'CampaignController@preview')->name('campaigns.preview');
  Route::get('/campaigns/{campaign}/dublicate', 'CampaignController@dublicate')->name('campaigns.dublicate');
  Route::get('/campaigns/{campaign}/send', 'CampaignController@sendView')->name('campaigns.sendview');
  Route::post('/campaigns/{campaign}/send', 'CampaignController@send')->name('campaigns.send');
  Route::post('/campaigns/{campaign}/test', 'CampaignController@testsend')->name('campaigns.testsend');
  Route::get('/reports', 'CampaignController@report')->name('campaigns.reports');

  Route::resource('/subscribers', 'SubscriberController');
  Route::get('/unsubs/{subscriber}', 'SubscriberController@unSubscribe')->name('subs.unsubscribe');
  Route::get('/subscribe/{subscriber}', 'SubscriberController@subscribe')->name('subs.subscribe');
  Route::post('/subscribers/import', 'SubscriberController@excelImport')->name('subs.import');

  Route::resource('/lists', 'ListController');
  Route::post('/massaction/{list}', 'ListController@action')->name('mass.action');
  Route::get('/subs/{list}', 'ListController@addSub')->name('subs.add');
  Route::get('/subs/{list}/{subscriber}/a', 'ListController@attachSub')->name('subs.attach');
  Route::get('/subs/{list}/{subscriber}/d', 'ListController@detachSub')->name('subs.detach');

  Route::get('/settings', 'SettingController@index')->name('settings');
  Route::post('/settings/main', 'SettingController@mainSettingStore')->name('settings.main');
  Route::post('/settings/mail', 'SettingController@mailSettingStore')->name('settings.mail');
  Route::post('/settings/personal', 'SettingController@personalSettingStore')->name('settings.personal');
  Route::post('/emailverification', 'SettingController@checkEmailVerification')->name('email.verification');
});

Route::prefix('api')->namespace('API')->middleware('auth')->group(function(){
  Route::get('get-template','TemplateController@getTemplate')->name('get.template');
  Route::get('templates', 'TemplateController@index')->name('api.templates');
  Route::post('upload', 'TemplateController@fileUploade')->name('file.upload');
});

//Tracker NO Auth
Route::get('/i/{subscriber}/{link}/{campaign}', 'MailTrackerController@click')->name('link.click');
Route::get('/o/{campaign}/{subscriber}', 'MailTrackerController@open')->name('open.tracker');
Route::get('/unsubscribe/{subscriber}/{campaign}', 'MailTrackerController@unsubscribe')->name('unsubscribe');
Route::get('/resubscribe/{subscriber}/{campaign}', 'MailTrackerController@resubscribe')->name('resubscribe');
Route::get('/test-complaint-bounce', 'MailTrackerController@test')->name('complaint.bounced');

Route::post('/bounces', 'MailTrackerController@bounced')->name('bounces');
Route::post('/complaints', 'MailTrackerController@complaint')->name('complaints');
Route::post('/campaigns/progress', 'CampaignController@progress')->name('campaigns.progress');

app/Subscriber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{

  protected $table = 'subscribers';
  protected $fillable = [
    'email',
    'name',
    'custom_fields',
    'bounced',
    'bounce_soft',
    'unsubscribe',
    'complaint',
    'last_campaign',
    'last_ares',
    'confirmed',
  ];

  public function scopeSendCampaign($query) {
    return $query->where('unsubscribed', '0')
                ->where('bounced', '0')
                ->where('complaint', '0')
                ->where('confirmed', '1');
  }

  public static function get_bounced_count($cid,$soft='')
  {
      if($soft=='soft') $subscribers = self::where('last_campaign', $cid)->where('bounce_soft', 1)->get();
      else $subscribers = self::where('last_campaign', $cid)->where('bounced', 1)->get();
      if (count($subscribers) > 0) {
          return count($subscribers);
      }
      else {
        return 0;
      }
  }

  public static function get_complaints_count($cid)
  {
    $subscribers = self::where('last_campaign', $cid)->where('complaint', 1)->get();
    if ($subscribers->count() > 0)
        return $subscribers->count();
    else
      return 0;
  }

  public static function get_unsubscribes_count($cid)
  {
      $subscribers = self::where('last_campaign', $cid)->where('unsubscribed', 1)->get();
      if ($subscribers->count() > 0)
          return $subscribers->count();
      else
          return 0;
  }



  public function lists()
  {
      return $this->belongsToMany('App\SubscriberList', 'subscriber_lists', 'subscriber_id', 'list_id');
  }
}

app/Http/Controllers/SubscriberController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSubscriberRequest;
use App\Http\Requests\UpdateSubscriberRequest;
use Illuminate\Http\Request;
use App\Subscriber;
use App\SubscriberList;
use Excel;
class SubscriberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( )
    {
      $subscribers = Subscriber::with('lists')->paginate(20);
      return view('subscribers.index')->withSubscribers($subscribers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lists = SubscriberList::all();
        return view('subscribers.create')->withLists($lists);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSubscriberRequest $request)
    {
        $subscriber = new Subscriber;
        $subscriber->name = $request->name;
        $subscriber->email = $request->email;
        $subscriber->save();
        $lists = $request->lists;
        if (!empty($lists)) {
          $subscriber->lists()->attach($lists);
        }

        return redirect()->back()->with('status', 'Подписчик успешно добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subscriber $subscriber)
    {
      $lists = SubscriberList::all();
      return view('subscribers.edit')->withLists($lists)->withSubscriber($subscriber);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSubscriberRequest $request, Subscriber $subscriber)
    {
      $subscriber->name = $request->name;
      $subscriber->email = $request->email;
      $subscriber->save();
      if (isset($request->lists)) {
        $subscriber->lists()->sync($request->lists);
      }else{
        $subscriber->lists()->sync(array());
      }
      return redirect()->action('SubscriberController@index')->with('status', 'Изменение успешно сохранены');
    }

    public function unSubscribe(Subscriber $subscriber)
    {
        $subscriber->unsubscribed = 1;
        $subscriber->save();
        return redirect()->back();
    }

    public function subscribe(Subscriber $subscriber)
    {
        $subscriber->unsubscribed = 0;
        $subscriber->confirmed = 1;
        $subscriber->save();
        return redirect()->back();
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subscriber $subscriber)
    {
        $subscriber->delete();
        return response()->json([
          'message' => 'Удаление прошло успешно.',
          'success' => true
        ]);
    }

    public function excelImport(Request $request)
    {
      $this->validate($request,[
        'file'=>'required|mimes:xlsx,xls'
      ]);

      if($request->hasFile('file'))
      {
          $path = $request->file('file')->getRealPath();
          $data = Excel::load($path, function($reader){})->get();
          if(!empty($data) && $data->count()){
            foreach ($data as $key => $value) {
              $subscriber = new Subscriber();
              $subscriber->name = $value->name;
              $subscriber->email = $value->email;
              $subscriber->save();
            }
          }
      }

      return back();
    }
}

resources/views/subscribers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
  <div class="card-header">
    добавить подписчика
  </div>
  <div class="card-body">
    <form action="{{ route('subscribers.store') }}" method="post">
      {{ csrf_field() }}
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Имя</label>
            <input type="text" name="name" value="" class="form-control">
          </div>
          <div class="form-group">
            <label>Email</label>
            <input type="text" name="email" value="" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}">
            @if ($errors->has('email'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
            @endif
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>Список</label>
            <select class="form-control" name="lists[]" multiple>
              @foreach($lists as $list)
                <option value="{{$list->id}}">{{$list->name}}</option>
              @endforeach
            </select>
          </div>
        </div>
      </div>

      <button type="submit" name="button"><i class="fas fa-plus"></i> Добавить</button>
    </form>
  </div>
</div>

@stop

resources/views/subscribers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
  <div class="card-header">
    добавить подписчика
  </div>
  <div class="card-body">
    <form action="{{ route('subscribers.update', $subscriber->id) }}" method="post">
      {{ csrf_field() }}
      {{method_field('PUT')}}
      <div class="form-group row">
        <div class="col-md-6">
          <label>Имя</label>
          <input type="text" name="name" value="{{$subscriber->name}}" class="form-control">
        </div>
        <div class="col-md-6">
          <label>Email</label>
          <input type="text" name="email" value="{{$subscriber->email}}" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}">
          @if ($errors->has('email'))
              <span class="invalid-feedback">
                  <strong>{{ $errors->first('email') }}</strong>
              </span>
          @endif
        </div>
      </div>
      <div class="form-group">
        <label>Список</label>
        <select id="lists" class="form-control" name="lists[]" multiple>
          @foreach($lists as $list)
            <option value="{{$list->id}}" >{{$list->name}}</option>
          @endforeach
        </select>
      </div>
      <button type="submit" name="button" class="btn btn-primary"><i class="fas fa-check"></i> Сохранить</button>
    </form>
  </div>
</div>

@endsection
@push('js')
<script>
    $(document).ready(function() {
        $('#lists').select2();
        $('#lists').select2().val({!! json_encode($subscriber->lists()->allRelatedIds()) !!}).trigger('change');
    });
</script>
@endpush

resources/views/subscribers/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <a href="{{route('subscribers.create')}}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Добавить подписчика">
            	<i class="fas fa-user-plus"></i>
            </a>
            <a href="javascript:void(0)" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal" data-toggle="tooltip" data-placement="top" title="Добавить подписчиков через EXCEL">
            	<i class="far fa-file-excel"></i>
            </a>
        </div>
        <div class="card-body" style="padding:10px 0 10px 0;">
          <table class="table table-striped table-condensed responsive" id="utable">
              <thead>
                <tr>
                  <th style="width: 20px;">#</th>
                  <th>Имя</th>
                  <th>Email</th>
                  <th class="text-center">{{trans('app.lists')}}</th>
                  <th class="text-center" style="width: 40px;">{{trans('app.date.active')}}</th>
                  <th class="text-center" style="width: 20px;">{{trans('app.status')}}</th>
                  <th class="text-center" style="width: 20px;">{{trans('app.action.unsubscribe')}}</th>
                  <th class="text-center" style="width: 20px;">{{trans('app.action.delete')}}</th>
                </tr>
              </thead>
              <tbody>
                @foreach($subscribers as $key=>$subscriber)
                  <tr>
                    <td>{{$key+1}}</td>
                    <td><a href="{{route('subscribers.edit', $subscriber->id)}}">{{$subscriber->name}}</a></td>
                    <td><a href="{{route('subscribers.edit', $subscriber->id)}}">{{$subscriber->email}}</a></td>
                    <td class="text-center">
                        @foreach($subscriber->lists as $list)
                            <span class="badge badge-primary">{{$list->name}}</span>
                        @endforeach
                    </td>
                    <td>{{date('d.m.Y H:i', strtotime($subscriber->updated_at))}}</td>
                    <td class="text-center">
                      @if($subscriber->bounced === 1)
                        <span class="badge badge-dark">Отскочила</span>
                      @elseif($subscriber->complaint === 1)
                        <span class="badge badge-dark">Отмечено как спам</span>
                      @elseif($subscriber->unsubscribed === 1)
                        <span class="badge badge-danger">Отписался</span>
                      @elseif($subscriber->confirmed === 0)
                        <span class="badge badge-warning">Неподтвержденный</span>
                      @else
                        <span class="badge badge-success">Подписан</span>
                      @endif
                    </td>
                    <td class="text-center">
                      @if($subscriber->bounced === 1 || $subscriber->complaint === 1)
                        -
                      @else
                        @if($subscriber->unsubscribed === 0 || is_null($subscriber->unsubscribed))
                          <a href="{{route('subs.unsubscribe', $subscriber->id)}}" style="color: red">
                            <i class="fas fa-ban" data-toggle="tooltip" data-placement="top" title="отписаться"></i>
                          </a>
                        @else
                          <a href="{{route('subs.subscribe', $subscriber->id)}}">
                            <i class="fas fa-check" data-toggle="tooltip" data-placement="top" title="подписка"></i>
                          </a>
                        @endif
                      @endif
                    </td>
                    <td class="text-center">
                        <a id="subscriber-delete" data-href="{{route('subscribers.destroy', $subscriber->id)}}"><i class="far fa-trash-alt" style="color: #000;"></i></a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <form action="{{route('subs.import')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Добавить подписчиков через EXCEL</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                Нужно указать <code>email</code> и <code>name</code> на первом строке в excel
                <div class="form-group">
                  <input type="file" name="file" value="" class="form-control">
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
              <button type="submit"class="btn btn-success" >Импортировать</button>
            </div>
          </form>
        </div>
      </div>
    </div>
@endsection
@push('js')
  @if(Session::has('errors'))
      <script>
          swal({
            title: "Ошибка!",
            text: "@foreach($errors->all() as $error) {{ $error }} @endforeach",
            icon: "error",
          })
      </script>
  @endif
  <script>
      $(document).on('click', '#subscriber-delete', function(e){
        var url = $(this).attr('data-href');
        subscribeDelete(url);
        e.preventDefault();
      });

      function subscribeDelete(url){
        swal({
            title: "Вы уверены?",
            text: "Вы действительно хотите удалить этого подписчика",
            icon: "warning",
            buttons: {
              cancel: "Отмена",
              confirm: "Да",
            },
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
              return new Promise(function(resolve) {
                 $.ajax({
                    url: url,
                    type: 'POST',
                    data: {_token: '{{csrf_token()}}', _method: 'DELETE'},
                    dataType: 'json',
                    success: function(data) {
                      swal('Удален!', data.message, 'success');
                      location.reload();
                    },
                    error: function(){
                      swal('Упсс...', 'Что-то пошло не так с ajax!', 'error');
                    }
                 });
              });
            }
        });
      }
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
  </script>
@endpush

resources/views/subscribers/subscribe.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content ">
                  <div class="card m-b-md">
                    <div class="card-body">
                      Вы успешно подписались на нашу рассылку
                    </div>
                  </div>
            </div>
        </div>
    </body>
</html>

resources/views/subscribers/unsubscribe.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content ">
                  <div class="card m-b-md">
                    <div class="card-header">
                      Вы успешно отписались от рассылки
                    </div>
                    <div class="card-body">
                      <a href="{{$link}}">Повторно подписаться?</a>
                    </div>
                  </div>
            </div>
        </div>
    </body>
</html>