routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware('auth')->group(function(){
  Route::get('/', 'CampaignController@index')->name('home');

  Route::resource('/templates', 'TemplateController');

  Route::resource('/campaigns', 'CampaignController');
  Route::get('/campaigns/{campaign}/preview', 'CampaignController@preview')->name('campaigns.preview');
  Route::get('/campaigns/{campaign}/dublicate', 'CampaignController@dublicate')->name('campaigns.dublicate');
  Route::get('/campaigns/{campaign}/send', 'CampaignController@sendView')->name('campaigns.sendview');
  Route::post('/campaigns/{campaign}/send', 'CampaignController@send')->name('campaigns.send');
  Route::post('/campaigns/{campaign}/test', 'CampaignController@testsend')->name('campaigns.testsend');
  Route::get('/reports', 'CampaignController@report')->name('campaigns.reports');

  Route::resource('/subscribers', 'SubscriberController');
  Route::get('/unsubs/{subscriber}', 'SubscriberController@unSubscribe')->name('subs.unsubscribe');
  Route::get('/subscribe/{subscriber}', 'SubscriberController@subscribe')->name('subs.subscribe');
  Route::post('/subscribers/import', 'SubscriberController@excelImport')->name('subs.import');

  Route::resource('/lists', 'ListController');
  Route::post('/massaction/{list}', 'ListController@action')->name('mass.action');
  Route::get('/subs/{list}', 'ListController@addSub')->name('subs.add');
  Route::get('/subs/{list}/{subscriber}/a', 'ListController@attachSub')->name('subs.attach');
  Route::get('/subs/{list}/{subscriber}/d', 'ListController@detachSub')->name('subs.detach');

  Route::get('/settings', 'SettingController@index')->name('settings');
  Route::post('/settings/main', 'SettingController@mainSettingStore')->name('settings.main');
  Route::post('/settings/mail', 'SettingController@mailSettingStore')->name('settings.mail');
  Route::post('/settings/personal', 'SettingController@personalSettingStore')->name('settings.personal');
  Route::post('/emailverification', 'SettingController@checkEmailVerification')->name('email.verification');
});

Route::prefix('api')->namespace('API')->middleware('auth')->group(function(){
  Route::get('get-template','TemplateController@getTemplate')->name('get.template');
  Route::get('templates', 'TemplateController@index')->name('api.templates');
  Route::post('upload', 'TemplateController@fileUploade')->name('file.upload');
});

//Tracker NO Auth
Route::get('/i/{subscriber}/{link}/{campaign}', 'MailTrackerController@click')->name('link.click');
Route::get('/o/{campaign}/{subscriber}', 'MailTrackerController@open')->name('open.tracker');
Route::get('/unsubscribe/{subscriber}/{campaign}', 'MailTrackerController@unsubscribe')->name('unsubscribe');
Route::get('/resubscribe/{subscriber}/{campaign}', 'MailTrackerController@resubscribe')->name('resubscribe');
Route::get('/test-complaint-bounce', 'MailTrackerController@test')->name('complaint.bounced');

Route::post('/bounces', 'MailTrackerController@bounced')->name('bounces');
Route::post('/complaints', 'MailTrackerController@complaint')->name('complaints');
Route::post('/campaigns/progress', 'CampaignController@progress')->name('campaigns.progress');

app/Http/Controllers/ListController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ListRequest;
use App\SubscriberList;
use App\Subscriber;
use Illuminate\Support\Facades\Storage;

class ListController extends Controller
{

    public function index()
    {
      $lists = SubscriberList::with('subscribers')->get();
      $active = array();
      $deactive = array();
      foreach ($lists as $key => $list) {
        $total[$list->id] = $list->subscribers->count();
        $active[$list->id] = $list->subscribers->where('unsubscribed', '0')
                          ->where('bounced', '0')
                          ->where('complaint', '0')
                          ->where('confirmed', '1')
                          ->count();
        $deactive[$list->id] = $list->subscribers->where('unsubscribed', '1')->count();
        $bounced[$list->id] = $list->subscribers->where('bounced', '1')->count();
      }

      return view('lists.index',compact('lists','active','deactive','bounced','total'));
    }

    public function create()
    {
        return view('lists.create');
    }

    public function store(ListRequest $request)
    {
        $lists = new SubscriberList;
        $lists->name = $request->name;
        $lists->save();
        return redirect()->action('ListController@index')->with('status', 'Список успешно добавлен');
    }

    public function show(Request $request, $id)
    {
      $list = SubscriberList::findOrFail($id);

      if($request->status === 'active') {
          $active = 'active';
          $subscribers = $list->subscribers->where('unsubscribed', '0')->where('bounced', '0')->where('complaint', '0')->where('confirmed', '1');
          return view('lists.show', compact('list', 'subscribers', 'active'));
      } else if($request->status === 'unconfirmed') {
          $active = 'unconfirmed';
          $subscribers = $list->subscribers->where('confirmed', 0);
          return view('lists.show', compact('list', 'subscribers', 'active'));
      } else if($request->status === 'unsubscribed') {
          $active = 'unsubscribed';
          $subscribers = $list->subscribers->where('unsubscribed', 1);
          return view('lists.show', compact('list', 'subscribers', 'active'));
      } else if($request->status === 'bounced') {
          $active = 'bounced';
          $subscribers = $list->subscribers->where('bounced', 1);
          return view('lists.show', compact('list', 'subscribers', 'active'));
      } else if($request->status === 'complaint') {
          $active = 'complaint';
          $subscribers = $list->subscribers->where('complaint', 1);
          return view('lists.show', compact('list', 'subscribers', 'active'));
      }

      $active = 'all';
      $subscribers = $list->subscribers;
      return view('lists.show', compact('list', 'subscribers', 'active'));
    }

    public function edit($id)
    {
        $list = SubscriberList::findOrFail($id);
        return view('lists.edit', compact('list'));
    }

    public function update(ListRequest $request, $id)
    {
      $lists = SubscriberList::findOrFail($id);
      $lists->name = $request->name;
      $lists->save();
      return redirect()->action('ListController@index')->with('status', 'Список успешно изменен');
    }

    public function addSub(SubscriberList $list)
    {
        $id = $list->id;
        $subscribers = Subscriber::orWhereDoesntHave('lists', function($query) use ($id) {
            $query->where('list_id', $id);
        })->get();
        return view('lists.subs.create', compact('list', 'subscribers'));
    }

    public function attachSub($lid, $sid)
    {
        $subscriber = Subscriber::findOrFail($sid);
        $subscriber->lists()->attach($lid);
        return redirect()->action('ListController@show', $lid)->with('status', 'Подписчик успешно добавлен в список');
    }

    public function detachSub($lid, $sid)
    {
        $subscriber = Subscriber::findOrFail($sid);
        $subscriber->lists()->detach($lid);
        return redirect()->route('lists.show', $lid)->with('status', 'Подписчик успешно удален из списка');
    }

    public function action(Request $request, $lid)
    {
        $msg = [
          'required' => 'Необходимо отметить хотя бы одного'
        ];
        $request->validate([
            'subscriber' => 'required'
        ],$msg);

        if($request->button === 'unsubscribe'){
            $subsids = $request->subscriber;
            foreach ($subsids as $sid) {
              $subscriber = Subscriber::findOrFail($sid);
              $subscriber->unsubscribed = 1;
              $subscriber->save();
            }
            return redirect()->back()->with('status', 'Отмеченные подписчики были отписаны');
        } else if($request->button === 'detach') {
            $subsids = $request->subscriber;
            foreach ($subsids as $sid) {
              $subscriber = Subscriber::findOrFail($sid);
              $subscriber->lists()->detach($lid);
            }
            return redirect()->back()->with('status', 'Отмеченные подписчики успешно удален из списка');
        } else {
            return back();
        }
    }

    public function destroy(SubscriberList $list)
    {
      $list->delete();
      return redirect()->route('lists.index')->with('status', 'Удаление прошло успешно.');
    }
}

resources/views/lists/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        {{ trans('app.action.create') }} список
    </div>
    <div class="card-body">
        <form action="{{route('lists.store')}}" method="post">
          {{ csrf_field() }}
          <div class="form-group">
            <label>{{ trans('app.name') }}</label>
            <input type="text" name="name" value="" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
          </div>
          <button type="submit" name="button" class="btn btn-dark"><i class="fas fa-plus"></i> Добавить</button>
        </form>
    </div>
</div>
@stop

resources/views/lists/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        Редактирования списка {{$list->name}}
    </div>
    <div class="card-body">
        <form action="{{route('lists.update', $list->id)}}" method="post">
          {{ csrf_field() }}
          {{method_field('PUT')}}
          <div class="form-group">
            <label>Названия</label>
            <input type="text" name="name" value="{{$list->name}}" class="form-control" required>
          </div>
          <button type="submit" name="button" class="btn btn-dark"><i class="fas fa-plus"></i> Изменить</button>
        </form>
    </div>
</div>
@stop

resources/views/lists/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <a href="{{route('lists.create')}}" class="btn btn-primary">
                <i class="fas fa-plus"></i> Создать список
            </a>
        </div>
        <div class="card-body" style="padding: 10px 0 10px 0;">
            <table class="table table-hover" id="utable">
            <thead>
                <tr>
                    <th style="width: 20px;">#</th>
                    <th>Названия</th>
                    <th style="width: 20px;" class="text-center">{{ trans('app.active') }}</th>
                    <th class="text-center">{{ trans('app.unsubscribers') }}</th>
                    <th class="text-center">{{ trans('app.bounced') }}</th>
                    <th style="width: 20px;" class="text-center">{{ trans('app.action.edit') }}</th>
                    <th style="width: 20px;" class="text-center">{{ trans('app.action.delete') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($lists as $k=>$list)
                    <tr>
                        <td>{{$k+1}}</td>
                        <td><a href="{{route('lists.show',$list->id)}}">{{$list->name}}</a></td>
                        <td class="text-center">
                          {{$active[$list->id]}}
                        </td>
                        <td class="text-center">
                          <span class="badge badge-secondary">
                            {{$total[$list->id] == 0 ? round($deactive[$list->id] * 100, 2) : round($deactive[$list->id] / ($total[$list->id]) * 100, 2)}}%
                          </span>
                          {{$deactive[$list->id]}} подписчик
                        </td>
                        <td class="text-center">
                          <span class="badge badge-secondary">
                            {{$total[$list->id] == 0 ? round($bounced[$list->id] * 100, 2) : round($bounced[$list->id] / ($total[$list->id]) * 100, 2)}}%
                          </span> {{$bounced[$list->id]}} подписчик
                        </td>
                        <td class="text-center"><a href="{{route('lists.edit',$list->id)}}"><i class="fas fa-edit"></i></a></td>
                        <td class="text-center">
                            <form action="{{action('ListController@destroy', $list->id)}}" method="post">
                                {{ csrf_field() }}
                                {{method_field('DELETE')}}
                                <button type="submit" class="btn btn-link"><i class="far fa-trash-alt" style="color: red;"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        </div>

    </div>
@stop

resources/views/lists/show.blade.php
@extends('layouts.app')

@section('content')

  <form method="POST" action="{{route('mass.action', $list->id)}}">
    {{ csrf_field() }}
    <h2 class="mb-3">Списки подписчиков</h2>
    <button class="btn btn-dark btn-sm" type="button" onclick="window.location='{{route('subs.add', $list->id)}}'"><i class="fas fa-plus"></i> Добавить подписчика в список</button>
    <button class="btn btn-dark btn-sm" type="submit" name="button" value="unsubscribe"><i class="fas fa-ban"></i> Отписка отмеченных</button>
    <button class="btn btn-dark btn-sm" type="submit" name="button" value="detach"><i class="far fa-trash-alt"></i> Убрать отмеченные из списка</button>
    <div class="card mt-3">
      <div class="card-body">
        Список: <span class="badge badge-primary">{{$list->name}}</span> | <a href="{{route('lists.index')}}" class="text-dark">Вернуться назад</a>
        <a href="{{route('lists.edit',$list->id)}}" class="ml-1 text-dark float-right"><i class="fas fa-wrench"></i> Настройки списка</a>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-12">
        <div id="container" style="min-height:200px;margin-top:20px;"></div>
      </div>
    </div>
    <div class="card" style="border: 0;">
      <div class="card-header pb-0 pl-0" style="background-color: #f9f9f9;">
        @include('lists.partials.nav', ['list' => $list, 'active' => $active])
      </div>
      <div class="card-body border-top-0" style="border: 1px solid rgba(0,0,0,.125); border-radius: 0px 0px 0.25rem 0.25rem; padding: 0;">
        <table class="table table-striped table-condensed responsive">
            <thead>
              <tr>
                <th></th>
                <th>Имя</th>
                <th>Email</th>
                <th class="text-center">Последняя активность</th>
                <th class="text-center" style="width: 20px;">Статус</th>
                <th class="text-center" style="width: 20px;">Отписаться</th>
                <th class="text-center" style="width: 20px;">Убрать</th>
              </tr>
            </thead>
            <tbody>
              @forelse($subscribers as $subscriber)
                <tr>
                  <td><input type="checkbox" name="subscriber[]" value="{{$subscriber->id}}"></td>
                  <td>{{$subscriber->name}}</td>
                  <td>{{$subscriber->email}}</td>
                  <td class="text-center">{{date('d.m.Y H:i', strtotime($subscriber->updated_at))}}</td>
                  <td>
                    @if($subscriber->bounced === 1)
                      <span class="badge badge-dark">Отскочила</span>
                    @elseif($subscriber->complaint === 1)
                      <span class="badge badge-dark">Отмечено как спам</span>
                    @elseif($subscriber->unsubscribed === 1)
                      <span class="badge badge-danger">Отписался</span>
                    @else
                      <span class="badge badge-success">Подписан</span>
                    @endif
                  </td>
                  <td class="text-center">
                    @if($subscriber->bounced === 1 || $subscriber->complaint === 1)
                      -
                    @else
                      @if($subscriber->unsubscribed === 0 || is_null($subscriber->unsubscribed))
                        <a href="{{route('subs.unsubscribe', $subscriber->id)}}" style="color: red">
                          <i class="fas fa-ban" data-toggle="tooltip" data-placement="top" title="отписаться"></i>
                        </a>
                      @else
                        <a href="{{route('subs.subscribe', $subscriber->id)}}">
                          <i class="fas fa-check" data-toggle="tooltip" data-placement="top" title="подписка"></i>
                        </a>
                      @endif
                    @endif
                  </td>
                  <td class="text-center">
                    <a href="{{route('subs.detach', [$list->id, $subscriber->id])}}">
                      <i class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Убрать из списка"></i>
                    </a>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="7" class="text-center"><h5>Нет данных</h5></td>
                </tr>
              @endforelse
            </tbody>
        </table>
      </div>
    </div>
  </form>

@stop
@push('js')
  @if(Session::has('errors'))
      <script>
          swal({
            title: "Ошибка!",
            text: "@foreach($errors->all() as $error) {{ $error }} @endforeach",
            icon: "error",
          })
      </script>
  @endif
  <script src="{{asset('js/highcharts/highcharts.js')}}"></script>
  <script type="text/javascript">
    var month = new Array();
      month[0]="Январь";
      month[1]="Фебраль";
      month[2]="Март";
      month[3]="Апрель";
      month[4]="Май";
      month[5]="Июнь";
      month[6]="Июль";
      month[7]="Август";
      month[8]="Сеньтябрь";
      month[9]="Октябрь";
      month[10]="Ноябьр";
      month[11]="Декабрь";
    var chart;
    $(document).ready(function() {
        Highcharts.setOptions({
            colors: ['#468847', '#B94A48', '#333333']
        });
        chart = new Highcharts.Chart({
            chart: {
              renderTo: 'container',
              type: 'areaspline',
              marginBottom: 25
            },
            title: {
              text: false
            },
            subtitle: {
              text: false
            },
            xAxis: {
              categories: [
                @php
                  $month_array = array();
                  $year_array = array();
                  $subs = $list->subscribers->where('unsubscribed', '0')
                                ->where('bounced', '0')
                                ->where('complaint', '0')
                                ->where('confirmed', '1')
                                ->last();
                  if(empty($subs->created_at)){
                    $month_max = time();
                  }else{
                    $month_max = strtotime($subs->created_at);
                  }

                  $month = strftime('%m', $month_max)-1;
                  $year = strftime('%y', $month_max);
                  for($i=0;$i<12;$i++)
                  {
                    array_push($month_array, $month);
                    array_push($year_array, $year);
                    $month--;
                    if($month<0)
                    {
                      $month = 11;
                      $year--;
                    }
                  }

                  $month_array = array_reverse($month_array);
                  $year_array = array_reverse($year_array);

                  for($i=0;$i<12;$i++)
                  {
                    echo 'month['.$month_array[$i].']'.'+" '.$year_array[$i].'"';
                    if($i<11)
                      echo ',';
                  }
                @endphp
              ]
            },
            yAxis: {
              title: {
                text: false
              },
              plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
              }]
            },
            plotOptions: {
              line: {
                stacking: 'normal'
              },
              series: {
                        marker: {
                            enabled: false
                        }
                    }
            },
            tooltip: {
              formatter: function() {
                  return '<b>'+ this.series.name +'</b><br/>'+
                  this.x +': '+ this.y;
              }
            },
            legend: {
              enabled: false
            },
            credits: {
                      enabled: false
                  },
            series: [{
                      name: 'Подписчики',
                      data: [
                        @php
                          $graph_array = array();
                          $onemonth = 2629746;
                          $maxmonth = $month_max;
                          for($i=0;$i<12;$i++)
                          {
                            $subscribers = $list->subscribers->where('created_at', '<=', date('Y-m-d H:i:s', $maxmonth))
                                          ->where('unsubscribed', '0')
                                          ->where('bounced', '0')
                                          ->where('complaint', '0')
                                          ->where('confirmed', '1')
                                          ->count();
                            if ($subscribers > 0)
                            {
                                array_push($graph_array, $subscribers);
                            }
                            else
                              array_push($graph_array, '0');

                            $maxmonth = $maxmonth - $onemonth;
                          }

                          $graph_array = array_reverse($graph_array);

                          for($i=0;$i<12;$i++)
                          {
                            echo $graph_array[$i];

                            if($i<11)
                            echo ',';
                          }

                        @endphp
                      ]
                  }]
        });
    });
  </script>
@endpush