routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware('auth')->group(function(){
  Route::get('/', 'CampaignController@index')->name('home');

  Route::resource('/templates', 'TemplateController');

  Route::resource('/campaigns', 'CampaignController');
  Route::get('/campaigns/{campaign}/preview', 'CampaignController@preview')->name('campaigns.preview');
  Route::get('/campaigns/{campaign}/dublicate', 'CampaignController@dublicate')->name('campaigns.dublicate');
  Route::get('/campaigns/{campaign}/send', 'CampaignController@sendView')->name('campaigns.sendview');
  Route::post('/campaigns/{campaign}/send', 'CampaignController@send')->name('campaigns.send');
  Route::post('/campaigns/{campaign}/test', 'CampaignController@testsend')->name('campaigns.testsend');
  Route::get('/reports', 'CampaignController@report')->name('campaigns.reports');

  Route::resource('/subscribers', 'SubscriberController');
  Route::get('/unsubs/{subscriber}', 'SubscriberController@unSubscribe')->name('subs.unsubscribe');
  Route::get('/subscribe/{subscriber}', 'SubscriberController@subscribe')->name('subs.subscribe');
  Route::post('/subscribers/import', 'SubscriberController@excelImport')->name('subs.import');

  Route::resource('/lists', 'ListController');
  Route::post('/massaction/{list}', 'ListController@action')->name('mass.action');
  Route::get('/subs/{list}', 'ListController@addSub')->name('subs.add');
  Route::get('/subs/{list}/{subscriber}/a', 'ListController@attachSub')->name('subs.attach');
  Route::get('/subs/{list}/{subscriber}/d', 'ListController@detachSub')->name('subs.detach');

  Route::get('/settings', 'SettingController@index')->name('settings');
  Route::post('/settings/main', 'SettingController@mainSettingStore')->name('settings.main');
  Route::post('/settings/mail', 'SettingController@mailSettingStore')->name('settings.mail');
  Route::post('/settings/personal', 'SettingController@personalSettingStore')->name('settings.personal');
  Route::post('/emailverification', 'SettingController@checkEmailVerification')->name('email.verification');
});

Route::prefix('api')->namespace('API')->middleware('auth')->group(function(){
  Route::get('get-template','TemplateController@getTemplate')->name('get.template');
  Route::get('templates', 'TemplateController@index')->name('api.templates');
  Route::post('upload', 'TemplateController@fileUploade')->name('file.upload');
});

//Tracker NO Auth
Route::get('/i/{subscriber}/{link}/{campaign}', 'MailTrackerController@click')->name('link.click');
Route::get('/o/{campaign}/{subscriber}', 'MailTrackerController@open')->name('open.tracker');
Route::get('/unsubscribe/{subscriber}/{campaign}', 'MailTrackerController@unsubscribe')->name('unsubscribe');
Route::get('/resubscribe/{subscriber}/{campaign}', 'MailTrackerController@resubscribe')->name('resubscribe');
Route::get('/test-complaint-bounce', 'MailTrackerController@test')->name('complaint.bounced');

Route::post('/bounces', 'MailTrackerController@bounced')->name('bounces');
Route::post('/complaints', 'MailTrackerController@complaint')->name('complaints');
Route::post('/campaigns/progress', 'CampaignController@progress')->name('campaigns.progress');

resources/views/templates/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('templates.store')}}" method="post">
    	{{ csrf_field() }}
    	<div class="row">
    		<div class="col-md-3">
    			<div class="form-group">
				    <label for="exampleInputEmail1">Названия шаблона</label>
				    <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" name="name" placeholder="Названия этого шаблона" autofocus>
            @if ($errors->has('name'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
				  </div>
				  <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i> Сохранить</button>
    		</div>
    		<div class="col-md-9">
    			<div class="form-group">
				    <label for="exampleInputEmail1">Тела шаблона</label>
				    <textarea name="body" id="body" class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" rows="3">{{old('body')}}</textarea>
            @if ($errors->has('body'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('body') }}</strong>
                </span>
            @endif
				  </div>

    		</div>
    	</div>

    </form>
@endsection

@push('js')
	<script>

    ckEditor = CKEDITOR.replace( 'body', {
      fullPage: true,
      allowedContent: true,
      filebrowserUploadUrl: '{{route('file.upload',['_token' => csrf_token() ])}}',
      height: '570px',
      extraPlugins: 'codemirror,filebrowser'
    });

    ckEditor.on("instanceReady",function() {
      ckEditor.addCommand( "save", {
        modes : { wysiwyg:1, source:1 },
        exec : function () {
          var theData = ckEditor.getData();
          if($('#name').val()){
            var name = $('#name').val()
          }else{
            var name = 'tem'
          }

          $.ajax({
             url: "{{route('templates.store')}}",
             type: 'POST',
             data: {_token: '{{csrf_token()}}', body: theData, name: name, ajax: true},
             dataType: 'json',
             success: function(data) {
                if(data.saved){
                  swal('Успешно выполнено!', data.message, 'success');
                }
                window.location = "{{route('templates.index')}}"
             },
             error: function(err){
               swal('Упсс...', 'Что-то пошло не так с ajax!', 'error');
             }
          });
        }
       });
    })
	</script>
@endpush

resources/views/templates/edit.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('templates.update', $template->id)}}" method="post">
    	{{ csrf_field() }}
        {{method_field('PUT')}}
    	<div class="row">
    		<div class="col-md-3">
    			<div class="form-group">
				    <label for="exampleInputEmail1">Названия шаблона</label>
				    <input type="text" class="form-control" id="exampleInputEmail1" name="name" placeholder="Названия этого шаблона" value="{{$template->name}}">
				  </div>
				  <button type="submit" class="btn btn-primary">Сохранить</button>
    		</div>
    		<div class="col-md-9">
    			<div class="form-group">
				    <label for="exampleInputEmail1">Тела шаблона</label>
				    <textarea name="body" id="body" class="form-control" rows="3">{!!$template->body!!}</textarea>
				  </div>

    		</div>
    	</div>

    </form>
@endsection

@push('js')
	<script>
    ckEditor = CKEDITOR.replace( 'body', {
      fullPage: true,
      allowedContent: true,
      filebrowserUploadUrl: '{{route('file.upload',['_token' => csrf_token() ])}}',
      height: '570px',
      extraPlugins: 'codemirror,filebrowser'
    });
    ckEditor.on("instanceReady",function() {
      ckEditor.addCommand( "save", {
        modes : { wysiwyg:1, source:1 },
        exec : function () {
          var theData = ckEditor.getData();
          alert('WEEEEE')
        }
       });
    })
	</script>
@endpush

resources/views/templates/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <a href="{{route('templates.create')}}" class="btn btn-primary">
                <i class="fas fa-plus"></i> Создать шаблон
            </a>
        </div>
        <div class="card-body" style="padding: 0;">
            <table class="table table-hover" id="users-table">
            <thead>
                <tr>
                    <th style="width: 20px;">#</th>
                    <th>Названия</th>
                    <th style="width: 20px;" class="text-center">Просмотр</th>
                    <th style="width: 20px;" class="text-center">Редактировать</th>
                    <th style="width: 20px;" class="text-center">Удалить</th>
                </tr>
            </thead>
            <tbody>
                @foreach($templates as $k=>$template)
                    <tr>
                        <td>{{$k+1}}</td>
                        <td><a href="{{route('templates.edit',$template->id)}}">{{$template->name}}</a></td>
                        <td class="text-center"><a href="{{route('templates.show',$template->id)}}"><i class="fas fa-eye"></i></a></td>
                        <td class="text-center"><a href="{{route('templates.edit',$template->id)}}"><i class="fas fa-edit"></i></a></td>
                        <td class="text-center">
                            <form action="{{action('TemplateController@destroy', $template->id)}}" method="post">
                                {{ csrf_field() }}
                                {{method_field('DELETE')}}
                                <button type="submit" class="btn btn-link"><i class="far fa-trash-alt" style="color: red;"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        </div>

    </div>
@stop

resources/views/templates/show.blade.php
{!! $template->body !!}