routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware('auth')->group(function(){
  Route::get('/', 'CampaignController@index')->name('home');

  Route::resource('/templates', 'TemplateController');

  Route::resource('/campaigns', 'CampaignController');
  Route::get('/campaigns/{campaign}/preview', 'CampaignController@preview')->name('campaigns.preview');
  Route::get('/campaigns/{campaign}/dublicate', 'CampaignController@dublicate')->name('campaigns.dublicate');
  Route::get('/campaigns/{campaign}/send', 'CampaignController@sendView')->name('campaigns.sendview');
  Route::post('/campaigns/{campaign}/send', 'CampaignController@send')->name('campaigns.send');
  Route::post('/campaigns/{campaign}/test', 'CampaignController@testsend')->name('campaigns.testsend');
  Route::get('/reports', 'CampaignController@report')->name('campaigns.reports');

  Route::resource('/subscribers', 'SubscriberController');
  Route::get('/unsubs/{subscriber}', 'SubscriberController@unSubscribe')->name('subs.unsubscribe');
  Route::get('/subscribe/{subscriber}', 'SubscriberController@subscribe')->name('subs.subscribe');
  Route::post('/subscribers/import', 'SubscriberController@excelImport')->name('subs.import');

  Route::resource('/lists', 'ListController');
  Route::post('/massaction/{list}', 'ListController@action')->name('mass.action');
  Route::get('/subs/{list}', 'ListController@addSub')->name('subs.add');
  Route::get('/subs/{list}/{subscriber}/a', 'ListController@attachSub')->name('subs.attach');
  Route::get('/subs/{list}/{subscriber}/d', 'ListController@detachSub')->name('subs.detach');

  Route::get('/settings', 'SettingController@index')->name('settings');
  Route::post('/settings/main', 'SettingController@mainSettingStore')->name('settings.main');
  Route::post('/settings/mail', 'SettingController@mailSettingStore')->name('settings.mail');
  Route::post('/settings/personal', 'SettingController@personalSettingStore')->name('settings.personal');
  Route::post('/emailverification', 'SettingController@checkEmailVerification')->name('email.verification');
});

Route::prefix('api')->namespace('API')->middleware('auth')->group(function(){
  Route::get('get-template','TemplateController@getTemplate')->name('get.template');
  Route::get('templates', 'TemplateController@index')->name('api.templates');
  Route::post('upload', 'TemplateController@fileUploade')->name('file.upload');
});

//Tracker NO Auth
Route::get('/i/{subscriber}/{link}/{campaign}', 'MailTrackerController@click')->name('link.click');
Route::get('/o/{campaign}/{subscriber}', 'MailTrackerController@open')->name('open.tracker');
Route::get('/unsubscribe/{subscriber}/{campaign}', 'MailTrackerController@unsubscribe')->name('unsubscribe');
Route::get('/resubscribe/{subscriber}/{campaign}', 'MailTrackerController@resubscribe')->name('resubscribe');
Route::get('/test-complaint-bounce', 'MailTrackerController@test')->name('complaint.bounced');

Route::post('/bounces', 'MailTrackerController@bounced')->name('bounces');
Route::post('/complaints', 'MailTrackerController@complaint')->name('complaints');
Route::post('/campaigns/progress', 'CampaignController@progress')->name('campaigns.progress');

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    // Campaign status
    const STATUS_DRAFT = 'draft';
    const STATUS_SENDING = 'sending';
    const STATUS_DONE = 'done';
    const STATUS_ERROR = 'error';
    const STATUS_QUEUE = 'queue';

    protected $fillable = [
      'name',
      'subject',
      'from_name',
      'from_email',
      'reply_to',
      'plain_text',
      'html_text',
      'query_string',
      'to_send',
      'status',
      'recipients',
      'timeout_check',
      'opens',
      'timezone',
      'errors',
      'run_date',
      'send_at',
      'complaint_setup',
      'bounce_setup'
    ];

    protected $dates = ['created_at', 'updated_at', 'run_date'];

    public function sending()
    {
        $this->status = self::STATUS_SENDING;
        $this->save();
    }

    public function draft()
    {
        $this->status = self::STATUS_DRAFT;
        $this->save();
    }

    public function done()
    {
        $this->status = self::STATUS_DONE;
        $this->send_at = \Carbon\Carbon::now();
        $this->save();
    }

    public function queue($datatime)
    {
        $this->status = self::STATUS_QUEUE;
        $this->run_date = $datatime;
        $this->save();
    }

    public function isSending(): bool
    {
        return $this->status === self::STATUS_SENDING;
    }

    public function isDraft(): bool
    {
        return $this->status === self::STATUS_DRAFT;
    }

    public function isDone(): bool
    {
        return $this->status === self::STATUS_DONE;
    }

    public function isQueue(): bool
    {
        return $this->status === self::STATUS_QUEUE;
    }

    public static function get_click_percentage($cid)
    {
      $campaign = self::findOrFail($cid);
      $clicks_join = '';
      $clicks_array = array();
      $clicks_unique = 0;

      foreach ($campaign->links as $link) {
        $clicks = $link->clicks;
        if($clicks!=''){
          $clicks_join .= $clicks.',';
        }
      }
      $clicks_array = explode(',', $clicks_join);
      $clicks_unique = count(array_unique($clicks_array));

      return $clicks_unique-1;
    }

    public function links()
    {
        return $this->belongsToMany('App\Link', 'campaign_links');
    }

    public function lists()
    {
        return $this->belongsToMany('App\SubscriberList', 'campaign_lists', 'campaign_id', 'list_id');
    }

    public function subscribers()
    {
        return $this->hasMany('App\Subscriber', 'last_campaign');
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreCampaignRequest;
use App\Http\Requests\SendRequest;
use App\Jobs\SendCampaignMails;
use App\Mail\SendCampaign;
use App\Campaign;
use App\Settings;
use App\Template;
use App\Subscriber;
use App\SubscriberList;
use App\Link;
use Carbon\Carbon;
use Mail;
use Helper;
use AWS;

class CampaignController extends Controller
{
    public function index()
    {
      $campaigns = Campaign::with('links')->get();
      $opens = array();
      $percentage_clicked = array();
      foreach ($campaigns as $key => $campaign) {
        if (empty($campaign->opens)){
          $opens[$campaign->id]['unique'] = '0';
          $opens[$campaign->id]['all'] = '0';
          $opens[$campaign->id]['per'] = '0';
        }
        else {
          $opens[$campaign->id]['unique'] = count(array_unique(explode(',', $campaign->opens)));
          $opens[$campaign->id]['all'] = count(explode(',', $campaign->opens));
          $opens[$campaign->id]['per'] = round($opens[$campaign->id]['unique']/($campaign->recipients-Subscriber::get_bounced_count($campaign->id)) * 100, 2);
        }

        if(empty($opens['all']))
            $opens[$campaign->id]['all'] = '0';

        if($campaign->recipients==0 || empty($campaign->recipients))
            $percentage_clicked[$campaign->id] = round(Campaign::get_click_percentage($campaign->id) *100, 2);
        else
            $percentage_clicked[$campaign->id] = round(Campaign::get_click_percentage($campaign->id)/$campaign->recipients *100, 2);
      }
      return view('campaigns.index',compact('campaigns', 'percentage_clicked', 'opens'));
    }

    public function report()
    {
      $campaigns = Campaign::with('links')->where('status', Campaign::STATUS_DONE)->get();
      $opens = array();
      $percentage_clicked = array();
      foreach ($campaigns as $key => $campaign) {
        if (empty($campaign->opens)){
          $opens[$campaign->id]['unique'] = '0';
          $opens[$campaign->id]['all'] = '0';
          $opens[$campaign->id]['per'] = '0';
        }
        else {
          $opens[$campaign->id]['unique'] = count(array_unique(explode(',', $campaign->opens)));
          $opens[$campaign->id]['all'] = count(explode(',', $campaign->opens));
          $opens[$campaign->id]['per'] = round($opens[$campaign->id]['unique']/($campaign->recipients-Subscriber::get_bounced_count($campaign->id)) * 100, 2);
        }

        if(empty($opens['all']))
          $opens[$campaign->id]['all'] = '0';

        if($campaign->recipients==0 || empty($campaign->recipients))
            $percentage_clicked[$campaign->id] = round(Campaign::get_click_percentage($campaign->id) *100, 2);
        else
            $percentage_clicked[$campaign->id] = round(Campaign::get_click_percentage($campaign->id)/$campaign->recipients *100, 2);
      }
      return view('campaigns.reports', compact('campaigns', 'percentage_clicked', 'opens'));
    }

    //Get template through AJAX for campaign
    public function getTemplate(Request $request)
    {
      $templates = Template::where('id', $request->tem_id)->pluck('body');
      return response()->json($templates);
    }

    public function dublicate(Campaign $campaign)
    {
        $dublicate = $campaign->replicate();
        $dublicate->to_send = null;
        $dublicate->recipients = null;
        $dublicate->send_at = null;
        $dublicate->run_date = null;
        $dublicate->status = 'draft';
        $dublicate->save();
        return redirect()->back();
    }

    public function create()
    {
        $default = array();
        $default['company_name'] = Settings::get('company_name');
        $default['from_name'] = Settings::get('from_name');
        $default['from_email'] = Settings::get('from_email');
        $default['reply_email'] = Settings::get('reply_email');
        $templates = Template::all();
        return view('campaigns.create',compact('templates','default'));
    }

    public function store(StoreCampaignRequest $request)
    {
        $campaign = new Campaign;
        $campaign->name = $request->name;
        $campaign->subject = $request->subject;
        $campaign->from_name = $request->from_name;
        $campaign->from_email = $request->from_email;
        $campaign->plain_text = $request->plain_text;
        $campaign->reply_to = $request->reply_email;
        $campaign->query_string = $request->query_string;
        $campaign->html_text = $request->body;
        $campaign->save();
        $campaign->draft();
        // return response()->json(['success' => true,'URL'=> action('CampaignController@sendView', $campaign->id)]);
        if($request->submit === 'save'){
          return redirect('/')->with('status', 'Рассылка сохранено');
        }else{
          return redirect()->action('CampaignController@sendView', $campaign->id);
        }

    }

    public function show(Campaign $campaign)
    {
      if ($campaign->send_at || $campaign->run_at) {
        $campaignOpen = array();
        $subscriberCount = array();
        $subscriberPercentage = array();
        $subscriberCount['bounced'] = Subscriber::get_bounced_count($campaign->id);
        $subscriberCount['unsubscribes'] = Subscriber::get_unsubscribes_count($campaign->id);
        $subscriberCount['complaints'] = Subscriber::get_complaints_count($campaign->id);
        $subscriberPercentage['unsubscribe'] = round($subscriberCount['unsubscribes']/($campaign->recipients-$subscriberCount['bounced']) * 100, 4);
        $subscriberPercentage['bounced'] = round(($subscriberCount['bounced']/$campaign->recipients) * 100, 2);
        $subscriberPercentage['complaint'] = round(($subscriberCount['complaints']/$campaign->recipients) * 100, 2);
        if (empty($campaign->opens)) {
          $campaignOpen['unique'] = '0';
          $campaignOpen['all'] = '0';
          $campaignOpen['percentage'] = '0';
        } else {
          $campaignOpen['unique'] = count(array_unique(explode(',', $campaign->opens)));
          $campaignOpen['all'] = count(explode(',', $campaign->opens));
          $campaignOpen['percentage'] = round($campaignOpen['unique']/($campaign->recipients-$subscriberCount['bounced']) * 100, 2);
        }
        $campaignOpen['click'] = Campaign::get_click_percentage($campaign->id);
        $campaignOpen['click_percentage'] = round($campaignOpen['click']/($campaign->recipients-$subscriberCount['bounced']) *100, 4);
        $campaignOpen['not'] = $campaign->recipients-$campaignOpen['unique']; //кол-во не открытых писем

        //Получение уникальных подписчиков из $campaign->opens
        $collection = array();
        $last_opens_array = explode(',', $campaign->opens);
        $loop_no = count(array_unique($last_opens_array));
        if($loop_no>10) $loop_no = 10;
        for($z=0;$z<$loop_no;$z++){
          $last_opens_array2 = array_reverse(array_unique($last_opens_array));
          $last_subscriber_id = explode(':', $last_opens_array2[$z]);
          $subs = Subscriber::where('id', $last_subscriber_id[0])->get();
          foreach($subs as $sub){
            $collection[$sub->id] = $sub;
          }
        }
        $subscribers = collect($collection);

        return view('campaigns.show', compact('campaign', 'campaignOpen', 'subscriberCount', 'subscriberPercentage', 'subscribers'));
      }
      else if(is_null($campaign->send_at) || is_null($campaign->run_at)){
        return redirect()->action('CampaignController@sendView', $campaign->id);
      }
    }

    public function preview(Campaign $campaign)
    {
        return view('campaigns.preview',compact('campaign'));
    }

    public function edit(Campaign $campaign)
    {
        $templates = Template::all();
        return view('campaigns.edit',compact('campaign','templates'));
    }

    public function update(StoreCampaignRequest $request, Campaign $campaign)
    {
      $campaign->name = $request->name;
      $campaign->subject = $request->subject;
      $campaign->from_name = $request->from_name;
      $campaign->from_email = $request->from_email;
      $campaign->plain_text = $request->plain_text;
      $campaign->reply_to = $request->reply_email;
      $campaign->query_string = $request->query_string;
      $campaign->html_text = $request->body;
      $campaign->save();
      if($request->submit === 'save'){
        return redirect('/')->with('status', 'Изменения сохранены');
      }else{
        return redirect()->action('CampaignController@sendView', $campaign->id);
      }
    }

    public function destroy(Campaign $campaign)
    {
        $campaign->delete();
        return redirect('/')->with('status', 'Удаление прошло успешно.');
    }

    public function sendView(Campaign $campaign)
    {
        $ses = AWS::createClient('ses')->getSendQuota([]);
        $lists = SubscriberList::all();
        return view('campaigns.send',compact('campaign','lists', 'ses'));
    }

    public function testsend(Request $request, Campaign $campaign)
    {
          $toemail = $request->email;
          Mail::send('mail.test', ['campaign' => $campaign,'toemail' => $request->email], function($message) use ($campaign, $toemail){
            $site_mail = $campaign->from_email;
            $site_name = $campaign->from_name;
            $message->from($site_mail, $site_name);
            $message->to($toemail, $toemail)->subject($campaign->subject);
          });
          return redirect()->action('CampaignController@sendView', $campaign->id)->with('status', 'Тестовый письмо отправлен');
    }

    public function send(SendRequest $request, Campaign $campaign)
    {
        $lists = $request->lists;
        $campaign->lists()->attach($lists);
        if ($request->submit === 'now'){
            $campaign->sending();
            Helper::parseUrl($campaign->id);
            dispatch(new SendCampaignMails($campaign));
            return redirect()->action('CampaignController@index')->with('status', 'Рассылка запущена');

resources/views/campaigns/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('campaigns.store')}}" method="post" id="form-campaign">
      {{ csrf_field() }}
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <label>Выбрать шаблон</label>
            <select class="form-control" id="listselect">
              <option value="1" disabled selected>Выбрать</option>
              @foreach($templates as $template)
                <option value="{{$template->id}}">{{$template->name}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group" id="title-field" style="display: none;">
            <label for="title">Названия</label>
            <input id="title" class="form-control" type="text" name="name" value="{{old('name')}}">
          </div>
          <div class="form-group">
            <label>Subject</label>
            <input id="subject" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" type="text" name="subject" value="{{old('subject')}}" autofocus>
            @if ($errors->has('subject'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('subject') }}</strong>
                </span>
            @endif
            <a href="javascript:void(0);" id="set-title-btn" data-original-title="" title="">Указать названия?</a>
          </div>
          <div class="form-group">
            <label>От имени</label>
            <input id="from_name" class="form-control" type="text" name="from_name" value="{{$default['from_name']}}">
          </div>
          <div class="form-group">
            <label>От еmail</label>
            <input id="from_email" class="form-control" type="text" name="from_email" value="{{$default['from_email']}}">
          </div>
          <div class="form-group">
            <label>Ответный еmail</label>
            <input id="reply_email" class="form-control" type="text" name="reply_email" value="{{$default['reply_email']}}">
          </div>
          <div class="form-group">
            <label>Простой текст</label>
            <textarea class="form-control" rows="2" name="plain_text"></textarea>
          </div>
          <div class="form-group">
            <label>
              Строка запроса
              <a class="btn btn-link" data-toggle="tooltip" data-placement="top"
                title="
                  При желании добавьте строку запроса ко всем ссылкам в бюллетене электронной почты.
                  Хорошим вариантом использования является отслеживание Google Analytics.
                  Не включать '?'
                  в строке запроса."
              >
                <i class="fas fa-question-circle"></i>
              </a>
            </label>
            <input type="text" name="query" class="form-control">
          </div>
          <!-- <div class="form-group">
            <label>Вложения</label>
            <input type="file" name="file" multiple>
            <small id="emailHelp" class="form-text text-muted">Допустимые типы файлов: jpeg, jpg, gif, png, pdf, zip</small>
          </div> -->
          <div class="row">
            <div class="col-sm-6">
              <button type="submit" name="submit" value="save" class="btn btn-success btn-sm" id="save-only"><i class="fas fa-check"></i> Сохранить</button>
            </div>
            <div class="col-sm-6" style="padding-left: 0px;">
              <button type="submit" name="submit" value="next" class="btn btn-primary btn-sm"><i class="fas fa-arrow-circle-right"></i> Сохранить и дальше</button>
            </div>
          </div>
        </div>
        <div class="col-md-9">
          <div class="form-group">
            <label>Контент</label>
            <textarea name="body" id="body" class="form-control" rows="5"></textarea>
          </div>
          @include('_includes.tags')
        </div>
      </div>

    </form>
@endsection

@push('js')
  <script>
      ckEditor = CKEDITOR.replace( 'body', {
        fullPage: true,
        allowedContent: true,
        filebrowserUploadUrl: '{{route('file.upload',['_token' => csrf_token() ])}}',
        height: '570px',
        extraPlugins: 'codemirror,filebrowser'
      });
      ckEditor.on("instanceReady",function() {
        ckEditor.addCommand( "save", {
          modes : { wysiwyg:1, source:1 },
          exec : function () {
            var theData = ckEditor.getData();
            alert('WEEEEE')
          }
         });
      })
  </script>
  <!-- <script>

      $('#form-campaign').submit(function(e){
        e.preventDefault();
        let form = $(this);
        form.find('.form-control').removeClass('is-invalid');
        form.find('.invalid-feedback').detach();
        const data = $('form').serialize();
        axios.post(this.action, data)
              .then((response) => {
                swal("Успешно выполнено!", " ", "success");
                if($('#save-only').click) {
                    window.location.href = '/'
                } else {
                    window.location.href = response.data.URL;
                }
              })
              .catch((error) => {
                let errors = error.response.data.errors;
                if($.isEmptyObject(errors)===false){
                  $.each(errors, (key, value)=>{
                    $('#'+key)
                    .addClass('is-invalid')
                    .closest('.form-group')
                    .append(`<span class="invalid-feedback"><strong>${value.join(", ")}</strong></span>`)
                  })
                }
              });
      })
  </script> -->
  <script type="text/javascript">
      $('#listselect').change(function () {
          var listid = $(this).find('option:selected').val();
          if (listid) {
              $.ajax({
                  type: "GET",
                  url: "{{route('get.template')}}?tem_id=" + listid,
                  success: function (res) {
                      if (res) {
                        $("textarea[name=body]").empty();
                        $("textarea[name=body]").text(res);
                        CKEDITOR.instances.body.setData(res)
                      } else {
                          console.log('NO')
                          $("textarea[name=body]").empty();
                      }
                  }
              });
          } else {
              $("textarea[name=body]").empty();
          }
      });
  </script>
  <script type="text/javascript">
			  $(document).ready(function() {
			  	$("#set-title-btn").click(function(){
			      	$(this).fadeOut();
			      	$("#set-title-btn-info").fadeOut();
			      	$("#title-field").slideDown("fast");
			      	$("#title").focus();
			  	});
			  	$("#title").blur(function(){
				  	if($(this).val()=='')
				  	{
					  	$("#set-title-btn").fadeIn();
					  	$("#set-title-btn-info").fadeIn();
				      $("#title-field").slideUp("fast");
			      }
			  	});
			  });
  </script>
@endpush

resources/views/campaigns/edit.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('campaigns.update', $campaign->id)}}" method="post">
      {{ csrf_field() }}
      {{method_field('PUT')}}
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <label>Выбрать шаблон</label>
            <select class="form-control" id="listselect">
              <option value="1" disabled selected>Выбрать</option>
              @foreach($templates as $template)
                <option value="{{$template->id}}">{{$template->name}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group" id="title-field" style="display: none;">
            <label for="title">Названия</label>
            <input id="title" class="form-control" type="text" name="name" value="{{$campaign->name}}">
          </div>
          <div class="form-group">
            <label>Subject</label>
            <input id="subject" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" type="text" name="subject" value="{{$campaign->subject}}" autofocus>
            @if ($errors->has('subject'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('subject') }}</strong>
                </span>
            @endif
            <a href="javascript:void(0);" id="set-title-btn" data-original-title="" title="">Указать названия?</a>
          </div>
          <div class="form-group">
            <label>От имени</label>
            <input class="form-control{{ $errors->has('from_name') ? ' is-invalid' : '' }}" type="text" name="from_name" value="{{$campaign->from_name}}">
            @if ($errors->has('from_name'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('from_name') }}</strong>
                </span>
            @endif
          </div>
          <div class="form-group">
            <label>От еmail</label>
            <input class="form-control{{ $errors->has('from_email') ? ' is-invalid' : '' }}" type="text" name="from_email" value="{{$campaign->from_email}}">
            @if ($errors->has('from_email'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('from_email') }}</strong>
                </span>
            @endif
          </div>
          <div class="form-group">
            <label>Ответный еmail</label>
            <input class="form-control{{ $errors->has('reply_email') ? ' is-invalid' : '' }}" type="text" name="reply_email" value="{{$campaign->reply_to}}">
            @if ($errors->has('reply_email'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('reply_email') }}</strong>
                </span>
            @endif
          </div>
          <div class="form-group">
            <label>Простой текст</label>
            <textarea class="form-control" rows="2" name="plain_text">{{$campaign->plain_text}}</textarea>
          </div>
          <div class="form-group">
            <label>
              Строка запроса
              <a class="btn btn-link" data-toggle="tooltip" data-placement="top"
                title="
                  При желании добавьте строку запроса ко всем ссылкам в бюллетене электронной почты.
                  Хорошим вариантом использования является отслеживание Google Analytics.
                  Не включать '?'
                  в строке запроса.
                "
              >
                <i class="fas fa-question-circle"></i>
              </a>
            </label>
            <input type="text" name="query_string" class="form-control" value="{{$campaign->query_string}}">
          </div>
          <!-- <div class="form-group">
            <label>Вложения</label>
            <input type="file" name="file" multiple>
            <small id="emailHelp" class="form-text text-muted">Допустимые типы файлов: jpeg, jpg, gif, png, pdf, zip</small>
          </div> -->
          <div class="row">
            <div class="col-sm-6">
              <button type="submit" name="submit" value="save" class="btn btn-success btn-sm"><i class="fas fa-check"></i> Сохранить</button>
            </div>
            <div class="col-sm-6" style="padding-left: 0px;">
              <button type="submit" name="submit" value="next" class="btn btn-primary btn-sm"><i class="fas fa-arrow-circle-right"></i> Сохранить и дальше</button>
            </div>
          </div>
        </div>
        <div class="col-md-9">
          <div class="form-group">
            <label>Контент</label>
            <textarea name="body" id="body" class="form-control" rows="5">{{$campaign->html_text}}</textarea>
          </div>
          @include('_includes.tags')
        </div>
      </div>

    </form>
@endsection

@push('js')
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous">
  </script>
  <script>
    ckEditor = CKEDITOR.replace( 'body', {
      fullPage: true,
      allowedContent: true,
      filebrowserUploadUrl: '{{route('file.upload',['_token' => csrf_token() ])}}',
      height: '570px',
      extraPlugins: 'codemirror,filebrowser'
    });
    ckEditor.on("instanceReady",function() {
      ckEditor.addCommand( "save", {
        modes : { wysiwyg:1, source:1 },
        exec : function () {
          var theData = ckEditor.getData();
          alert('WEEEEE')
        }
       });
    })
  </script>
    <script type="text/javascript">
      $('#listselect').change(function () {
          var listid = $(this).find('option:selected').val();
          if (listid) {
              $.ajax({
                  type: "GET",
                  url: "{{route('get.template')}}?tem_id=" + listid,
                  success: function (res) {
                      if (res) {
                        $("textarea[name=body]").empty();
                        $("textarea[name=body]").text(res);
                        CKEDITOR.instances.body.setData(res)
                      } else {
                          console.log('NO')
                          $("textarea[name=body]").empty();
                      }
                  }
              });
          } else {
              $("textarea[name=body]").empty();
          }
      });

  </script>
  <script type="text/javascript">
        $(document).ready(function() {
          $("#set-title-btn").click(function(){
              $(this).fadeOut();
              $("#set-title-btn-info").fadeOut();
              $("#title-field").slideDown("fast");
              $("#title").focus();
          });
          $("#title").blur(function(){
            if($(this).val()=='')
            {
              $("#set-title-btn").fadeIn();
              $("#set-title-btn-info").fadeIn();
              $("#title-field").slideUp("fast");
            }
          });
        });
  </script>
@endpush

resources/views/campaigns/preview.blade.php
{!! $campaign->html_text !!}